### ISSUE TITLE
Throws `IllegalArgumentException` on registration of very short text.

### ISSUE THREAD

**Issue by fuji44** [toposoid/toposoid-knowledge-register-web#1]
Based on the following source code, I am running it in an environment built with `docker-compose up`.

https://github.com/toposoid/toposoid/tree/4922699ba45c43dc1b32d9c2b674ec38501eb1b2

When the following command is executed, the response will be returned normally, but the console will output the error described below.

```shell
$ curl --request POST \
  --url http://localhost:9002/regist \
  --header 'Content-Type: application/json' \
  --data '{
  "knowledgeList": [
    {
      "sentence": "セリヌンティウスである。",
      "json": "{}"
    }
  ]
}'
"result":"OK"
```

```shell
toposoid-knowledge-register-web_1            | 2021-10-22 13:45:38 ERROR actors.RegistKnowledgeActor  java.lang.IllegalArgumentException: Cypher query text should not be an empty string
toposoid-knowledge-register-web_1            | java.lang.IllegalArgumentException: Cypher query text should not be an empty string
toposoid-knowledge-register-web_1            |  at org.neo4j.driver.internal.util.Preconditions.checkArgument(Preconditions.java:38)
toposoid-knowledge-register-web_1            |  at org.neo4j.driver.Query.validateQueryText(Query.java:204)
toposoid-knowledge-register-web_1            |  at org.neo4j.driver.Query.<init>(Query.java:56)
toposoid-knowledge-register-web_1            |  at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37)
toposoid-knowledge-register-web_1            |  at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:55)
toposoid-knowledge-register-web_1            |  at com.ideal.linked.data.accessor.neo4j.Neo4JAccessor$.$anonfun$executeQuery$1(Neo4JAccessor.scala:36)
toposoid-knowledge-register-web_1            |  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
toposoid-knowledge-register-web_1            |  at scala.util.Try$.apply(Try.scala:213)
toposoid-knowledge-register-web_1            |  at com.ideal.linked.data.accessor.neo4j.Neo4JAccessor$.executeQuery(Neo4JAccessor.scala:33)
toposoid-knowledge-register-web_1            |  at com.ideal.linked.toposoid.sentence.transformer.neo4j.Sentence2Neo4jTransformer$.$anonfun$createGraphAuto$1(Sentence2Neo4jTransformer.scala:52)
toposoid-knowledge-register-web_1            |  at com.ideal.linked.toposoid.sentence.transformer.neo4j.Sentence2Neo4jTransformer$.$anonfun$createGraphAuto$1$adapted(Sentence2Neo4jTransformer.scala:45)
toposoid-knowledge-register-web_1            |  at scala.collection.immutable.List.foreach(List.scala:431)
toposoid-knowledge-register-web_1            |  at com.ideal.linked.toposoid.sentence.transformer.neo4j.Sentence2Neo4jTransformer$.createGraphAuto(Sentence2Neo4jTransformer.scala:45)
toposoid-knowledge-register-web_1            |  at actors.RegistKnowledgeActor$$anonfun$receive$1.applyOrElse(KnowledgeRegistActor.scala:45)
toposoid-knowledge-register-web_1            |  at akka.actor.Actor.aroundReceive(Actor.scala:537)
toposoid-knowledge-register-web_1            |  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
toposoid-knowledge-register-web_1            |  at actors.RegistKnowledgeActor.aroundReceive(KnowledgeRegistActor.scala:34)
toposoid-knowledge-register-web_1            |  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
toposoid-knowledge-register-web_1            |  at akka.actor.ActorCell.invoke(ActorCell.scala:547)
toposoid-knowledge-register-web_1            |  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
toposoid-knowledge-register-web_1            |  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
toposoid-knowledge-register-web_1            |  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
toposoid-knowledge-register-web_1            |  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
toposoid-knowledge-register-web_1            |  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
toposoid-knowledge-register-web_1            |  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
toposoid-knowledge-register-web_1            |  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
toposoid-knowledge-register-web_1            |  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I did some additional test cases and wrote down the results as well.

- ❌ : セリヌンティウスである。
- ❌ : セリヌンティウスである
- ❌ : セリヌンティウスです。
- ❌ : セリヌンティウスでした。
- ❌ : セリヌンティウス
- ✅ : メロスには竹馬の友があった。セリヌンティウスである。
- ✅ : 彼はセリヌンティウスである。
- ✅ : 彼はセリヌンティウスである
- ✅ : 彼はセリヌンティウスです。
- ✅ : 彼はセリヌンティウスでした。
- ✅ : 彼はセリヌンティウス

Do I need to change the text I specify for `sentence` to get around this problem?
Ideally, I would like to be able to register `セリヌンティウスである。` as it is.

**Comment by makoto-kubodera** [comment]
Thank you for pointing out the issue. @fuji44
This is a bug and we will investigate and fix it.

**Comment by makoto-kubodera** [comment]
This bug has been fixed. I also built and uploaded docker image.
If you want to check, try docker-compose up after deleting the Docker Image of toposoid-knowledge-register-web.  
If that doesn't work, try deleting the image below as well. @fuji44 

- toposoid/toposoid-deduction-unit-exact-match-web
- toposoid/toposoid-deduction-unit-synonym-match-web
- toposoid/toposoid-component-dispatcher-web
- toposoid/toposoid-deduction-admin-web
- toposoid/toposoid-core

**Comment by fuji44** [comment]
Thanks, I can now register.
